version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: passin-postgres
    environment:
      POSTGRES_USER: passin
      POSTGRES_PASSWORD: passin
      POSTGRES_DB: passin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data55sss5:/var/lib/postgresql/data

volumes:
  postgres_data55sss5: