version: '3.8'
services:
  pg_passin2:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=passin
      - POSTGRES_PASSWORD=passin
      - POSTGRES_DB=passin
      - TZ=America/Sao_Paulo
    volumes:
      - pg_server_passin3:/bitnami/postgresql

  app:
    build: .
    ports:
      - "5273:5273"
    environment:
      DATABASE_URL: postgresql://passin:passin@pg_passin2:5432/passin
    depends_on:
      - pg_passin2
    volumes:
      - server_api:/app
    env_file:
      - .env
    command: >
      sh -c "
      /wait-for-it.sh pg_passin2:5432 -- npm run db:generate &&
      /wait-for-it.sh pg_passin2:5432 -- npm run db:migrate &&
      /wait-for-it.sh pg_passin2:5432 -- npm run seed &&
      npm run start
      "

volumes:
  pg_server_passin3:
  server_api:
